### ISSUE TITLE
Is the paper available?

### ISSUE THREAD

**Issue by camillychen** [VTCC-uTVM/2022AICityChallenge-Track3#2]
Dear Sir:

When can release paper that try your implement?

thank you

**Comment by VTCC-uTVM** [comment]
Our paper is published here, [An Effective Temporal Localization Method With Multi-View 3D Action Recognition for Untrimmed Naturalistic Driving Videos](https://openaccess.thecvf.com/content/CVPR2022W/AICity/html/Tran_An_Effective_Temporal_Localization_Method_With_Multi-View_3D_Action_Recognition_CVPRW_2022_paper.html)
